# Generated by Django 4.1.4 on 2022-12-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_api', '0005_image_gray'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
