# Generated by Django 4.1.4 on 2022-12-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_api', '0010_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
