# Generated by Django 4.1.4 on 2022-12-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_api', '0007_remove_image_gray_image_modified_alter_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
