# Generated by Django 4.1.4 on 2022-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_api', '0008_remove_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='original.png', upload_to='original/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='modified',
            field=models.ImageField(default='modified.png', upload_to='modified/'),
        ),
    ]
