# Generated by Django 4.1.4 on 2022-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_api', '0006_delete_employee_delete_product_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gray',
        ),
        migrations.AddField(
            model_name='image',
            name='modified',
            field=models.ImageField(default=1, upload_to='modified/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='original/'),
        ),
    ]
